@baseUrl = http://localhost:4000/api

### 1. Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!"
}

###

### 2. Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!"
}

###

### Access Token
@accessToken = {{login.response.body.data.access_token}}

###

### 3. Get Me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}
