@baseUrl = http://localhost:4000/api

### 1. Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!"
}

###

### Auth Token
@accessToken = {{login.response.body.data.access_token}}

###

### 2. Create Mindmap
# @name createMindmap
POST {{baseUrl}}/mindmaps
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Test Mindmap"
}

###

### Mindmap Id
@mindmapId = {{createMindmap.response.body.data.id}}

###

### 3. List Mindmaps
GET {{baseUrl}}/mindmaps
Authorization: Bearer {{accessToken}}

###

### 4. Get Mindmap
GET {{baseUrl}}/mindmaps/{{mindmapId}}
Authorization: Bearer {{accessToken}}

###

### 5. Update Mindmap
PUT {{baseUrl}}/mindmaps/{{mindmapId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Updated Title"
}

###

### 6. Delete Mindmap
DELETE {{baseUrl}}/mindmaps/{{mindmapId}}
Authorization: Bearer {{accessToken}}
